// An object that know all the ALLOWED ACTION TYPES
// ~ contract or standard
const ActionTypes = {
    // Category
    CATEGORIES_ALL_REQ: 'CATEGORIES_ALL_REQ',
    CATEGORIES_ALL_OK:  'CATEGORIES_ALL_OK',
    CATEGORIES_ALL_X:   'CATEGORIES_ALL_X',

    CATEGORY_ADD_REQ:   'CATEGORY_ADD_REQ',
    CATEGORY_ADD_OK:    'CATEGORY_ADD_OK',
    CATEGORY_ADD_X:     'CATEGORY_ADD_X',

    //CATEGORY_RANDOMIZED_REQ: 'CATEGORY_RANDOMIZED_REQ',
    //CATEGORY_RANDOMIZED_OK: 'CATEGORY_RANDOMIZED_OK',
    //CATEGORY_RANDOMIZED_X: 'CATEGORY_RANDOMIZED_X',

    //CATEGORY_CURRENT_RESET_REQ: 'CATEGORY_CURRENT_RESET_REQ',
    //CATEGORY_CURRENT_RESET_OK: 'CATEGORY_CURRENT_RESET_OK',
    //CATEGORY_CURRENT_RESET_X: 'CATEGORY_CURRENT_RESET_X',

    CATEGORY_DELETE_REQ: 'CATEGORY_DELETE_REQ',
    CATEGORY_DELETE_OK: 'CATEGORY_DELETE_OK',
    CATEGORY_DELETE_X: 'CATEGORY_DELETE_X',
};

export default ActionTypes;